# Generated by Django 4.1.4 on 2022-12-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='zip',
            field=models.CharField(default='000', max_length=255),
        ),
    ]
